# Generated by Django 5.2.17 on 2026-09-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BizUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cstg_uid', models.CharField(help_text='CoStage 本地用户 id（纯数字串，如 "2"）；trusted 模式下为 x-trusted-<业务userId>', max_length=64, unique=True, verbose_name='CoStage uid')),
                ('username', models.CharField(max_length=64, verbose_name='业务用户名')),
                ('role', models.CharField(choices=[('teacher', '教师'), ('student', '学生'), ('guest', '访客')], default='student', max_length=16, verbose_name='业务角色')),
                ('status', models.CharField(choices=[('active', '正常'), ('suspended', '暂停'), ('banned', '禁播封禁')], default='active', max_length=16, verbose_name='账号状态')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '业务用户',
                'verbose_name_plural': '业务用户',
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('action', models.CharField(max_length=32, verbose_name='动作')),
                ('user_id', models.CharField(max_length=64, verbose_name='userId')),
                ('room_id', models.CharField(blank=True, max_length=64, verbose_name='roomId')),
                ('allow', models.BooleanField(verbose_name='放行')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='拒绝理由')),
                ('request_id', models.CharField(blank=True, max_length=64, verbose_name='幂等键')),
            ],
            options={
                'verbose_name': '决策日志',
                'verbose_name_plural': '决策日志',
                'ordering': ['-ts'],
            },
        ),
    ]
