# Generated by Django 5.2.17 on 2026-09-12 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='分类名')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('action', models.CharField(max_length=32, verbose_name='动作')),
                ('user_id', models.CharField(max_length=64, verbose_name='CoStage userId')),
                ('room_id', models.CharField(blank=True, max_length=64, verbose_name='房间')),
                ('allow', models.BooleanField(verbose_name='放行')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='拒绝理由')),
                ('request_id', models.CharField(blank=True, max_length=64, verbose_name='幂等键')),
            ],
            options={
                'verbose_name': '决策日志',
                'verbose_name_plural': '决策日志',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('pending_payment', '待支付'), ('paid', '已支付/待发货'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending_payment', max_length=16, verbose_name='状态')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总额')),
                ('receiver', models.CharField(max_length=32, verbose_name='收货人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(max_length=200, verbose_name='配送地址')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='订单备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='顾客')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商品名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('unit', models.CharField(default='件', max_length=8, verbose_name='单位')),
                ('barcode', models.CharField(blank=True, max_length=32, verbose_name='条码')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='商品描述')),
                ('on_shelf', models.BooleanField(default=True, verbose_name='上架中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建档时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='supermarket.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64, verbose_name='商品名快照')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交单价快照')),
                ('qty', models.PositiveIntegerField(verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supermarket.order', verbose_name='订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supermarket.product', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', '顾客'), ('staff', '店员'), ('manager', '经理')], default='customer', max_length=16, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='顾客')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车项',
                'verbose_name_plural': '购物车项',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
