# Generated by Django 5.2.17 on 2026-09-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='co_stage_uid',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='CoStage uid'),
        ),
    ]
